package com.litongjava.telegram.bot.model;

import com.litongjava.db.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("bot_channel", "channel_id", BotChannel.class);
		arp.addMapping("convoy", "id", Convoy.class);
		arp.addMapping("setting", "id", Setting.class);
		arp.addMapping("telegram_channel_full", "id", TelegramChannelFull.class);
		arp.addMapping("telegram_channel_min", "id", TelegramChannelMin.class);
		arp.addMapping("telegram_channel_participants", "id", TelegramChannelParticipants.class);
		arp.addMapping("telegram_state", "id", TelegramState.class);
		arp.addMapping("tio_boot_admin_sa_token", "id", TioBootAdminSaToken.class);
		arp.addMapping("tio_boot_admin_system_constants_config", "id", TioBootAdminSystemConstantsConfig.class);
		arp.addMapping("tio_boot_admin_system_users", "id", TioBootAdminSystemUsers.class);
		arp.addMapping("user_role", "tg_id", UserRole.class);
	}
}


