package com.litongjava.telegram.bot.model;

import com.litongjava.telegram.bot.model.base.BaseBotChannel;

/**
 * Generated by java-db.
 */
public class BotChannel extends BaseBotChannel<BotChannel> {
  private static final long serialVersionUID = 1L;
	public static final BotChannel dao = new BotChannel().dao();
	/**
	 * 
	 */
  public static final String tableName = "bot_channel";
  public static final String primaryKey = "channel_id";
  // private java.lang.String channelId
  // private java.lang.String tgId
  // private java.lang.String channelName
  // private java.lang.Integer count
  // private java.lang.String url
  // private java.lang.String role
  // private java.lang.String chatType
  // private java.lang.Integer carId
  // private java.lang.String messageId
  // private java.lang.Integer status
  // private java.util.Date createTime
  // private java.util.Date updateTime
  // private java.lang.Long accessHash
  // private java.lang.Integer deleted
  // private java.lang.Integer isAdmin

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

