package com.litongjava.telegram.bot.model;

import com.litongjava.telegram.bot.model.base.BaseConvoy;

/**
 * Generated by java-db.
 */
public class Convoy extends BaseConvoy<Convoy> {
  private static final long serialVersionUID = 1L;
	public static final Convoy dao = new Convoy().dao();
	/**
	 * 
	 */
  public static final String tableName = "convoy";
  public static final String primaryKey = "id";
  // private java.lang.Integer id
  // private java.lang.String name
  // private java.lang.Integer joinCount
  // private java.lang.Integer count
  // private java.lang.Integer num
  // private java.lang.String chatType

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

