package com.litongjava.telegram.bot.model;

import com.litongjava.telegram.bot.model.base.BaseSetting;

/**
 * Generated by java-db.
 */
public class Setting extends BaseSetting<Setting> {
  private static final long serialVersionUID = 1L;
	public static final Setting dao = new Setting().dao();
	/**
	 * 
	 */
  public static final String tableName = "setting";
  public static final String primaryKey = "id";
  // private java.lang.String setKey
  // private java.lang.String setValue
  // private java.math.BigInteger id

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

