package com.litongjava.telegram.bot.model;

import com.litongjava.telegram.bot.model.base.BaseTelegramState;

/**
 * Generated by java-db.
 */
public class TelegramState extends BaseTelegramState<TelegramState> {
  private static final long serialVersionUID = 1L;
	public static final TelegramState dao = new TelegramState().dao();
	/**
	 * 
	 */
  public static final String tableName = "telegram_state";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.Integer pts
  // private java.lang.Integer qts
  // private java.lang.Integer date
  // private java.lang.Integer seq
  // private java.lang.Integer unreadCount
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

