package com.litongjava.telegram.bot.model;

import com.litongjava.telegram.bot.model.base.BaseTelegramChannelMin;

/**
 * Generated by java-db.
 */
public class TelegramChannelMin extends BaseTelegramChannelMin<TelegramChannelMin> {
  private static final long serialVersionUID = 1L;
	public static final TelegramChannelMin dao = new TelegramChannelMin().dao();
	/**
	 * 
	 */
  public static final String tableName = "telegram_channel_min";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.String json
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

