package com.litongjava.telegram.bot.model;

import com.litongjava.telegram.bot.model.base.BaseTioBootAdminSaToken;

/**
 * Generated by java-db.
 */
public class TioBootAdminSaToken extends BaseTioBootAdminSaToken<TioBootAdminSaToken> {
  private static final long serialVersionUID = 1L;
	public static final TioBootAdminSaToken dao = new TioBootAdminSaToken().dao();
	/**
	 * 
	 */
  public static final String tableName = "tio_boot_admin_sa_token";
  public static final String primaryKey = "id";
  // private java.lang.String id
  // private java.lang.String value
  // private java.lang.Long timeout
  // private byte[] ob
  // private java.lang.Long obTimeout
  // private java.lang.String remark
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

