package com.litongjava.telegram.bot.model;

import com.litongjava.telegram.bot.model.base.BaseTioBootAdminSystemConstantsConfig;

/**
 * Generated by java-db.
 */
public class TioBootAdminSystemConstantsConfig extends BaseTioBootAdminSystemConstantsConfig<TioBootAdminSystemConstantsConfig> {
  private static final long serialVersionUID = 1L;
	public static final TioBootAdminSystemConstantsConfig dao = new TioBootAdminSystemConstantsConfig().dao();
	/**
	 * 
	 */
  public static final String tableName = "tio_boot_admin_system_constants_config";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.String keyName
  // private java.lang.String keyValue
  // private java.lang.String remark
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

