package com.litongjava.telegram.bot.model;

import com.litongjava.telegram.bot.model.base.BaseTioBootAdminSystemUsers;

/**
 * Generated by java-db.
 */
public class TioBootAdminSystemUsers extends BaseTioBootAdminSystemUsers<TioBootAdminSystemUsers> {
  private static final long serialVersionUID = 1L;
	public static final TioBootAdminSystemUsers dao = new TioBootAdminSystemUsers().dao();
	/**
	 * 
	 */
  public static final String tableName = "tio_boot_admin_system_users";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.String username
  // private java.lang.String password
  // private java.lang.String nickname
  // private java.lang.String signature
  // private java.lang.String title
  // private java.lang.String groupName
  // private java.lang.String tags
  // private java.lang.Integer notifyCount
  // private java.lang.Integer unreadCount
  // private java.lang.String country
  // private java.lang.String access
  // private java.lang.String geographic
  // private java.lang.String address
  // private java.lang.String remark
  // private java.lang.Long deptId
  // private java.lang.String postIds
  // private java.lang.String email
  // private java.lang.String phone
  // private java.lang.Integer sex
  // private java.lang.String avatar
  // private java.lang.Integer status
  // private java.lang.String loginIp
  // private java.util.Date loginDate
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

