package com.litongjava.telegram.bot.model;

import com.litongjava.telegram.bot.model.base.BaseUserRole;

/**
 * Generated by java-db.
 */
public class UserRole extends BaseUserRole<UserRole> {
  private static final long serialVersionUID = 1L;
	public static final UserRole dao = new UserRole().dao();
	/**
	 * 
	 */
  public static final String tableName = "user_role";
  public static final String primaryKey = "tg_id";
  // private java.lang.String tgId
  // private java.lang.String role
  // private java.util.Date createdAt
  // private java.util.Date updatedAt

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

