package com.litongjava.telegram.bot.model.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseConvoy<M extends BaseConvoy<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public M setJoinCount(java.lang.Integer joinCount) {
		set("join_count", joinCount);
		return (M)this;
	}
	
	public java.lang.Integer getJoinCount() {
		return getInt("join_count");
	}
	
	public M setCount(java.lang.Integer count) {
		set("count", count);
		return (M)this;
	}
	
	public java.lang.Integer getCount() {
		return getInt("count");
	}
	
	public M setNum(java.lang.Integer num) {
		set("num", num);
		return (M)this;
	}
	
	public java.lang.Integer getNum() {
		return getInt("num");
	}
	
	public M setChatType(java.lang.String chatType) {
		set("chat_type", chatType);
		return (M)this;
	}
	
	public java.lang.String getChatType() {
		return getStr("chat_type");
	}
	
}

