package com.litongjava.telegram.bot.model.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBotChannel<M extends BaseBotChannel<M>> extends Model<M> implements IBean {

	/**
	 * 群id
	 */
	public M setChannelId(java.lang.String channelId) {
		set("channel_id", channelId);
		return (M)this;
	}
	
	/**
	 * 群id
	 */
	public java.lang.String getChannelId() {
		return getStr("channel_id");
	}
	
	public M setTgId(java.lang.String tgId) {
		set("tg_id", tgId);
		return (M)this;
	}
	
	public java.lang.String getTgId() {
		return getStr("tg_id");
	}
	
	/**
	 * 群名称
	 */
	public M setChannelName(java.lang.String channelName) {
		set("channel_name", channelName);
		return (M)this;
	}
	
	/**
	 * 群名称
	 */
	public java.lang.String getChannelName() {
		return getStr("channel_name");
	}
	
	public M setCount(java.lang.Integer count) {
		set("count", count);
		return (M)this;
	}
	
	public java.lang.Integer getCount() {
		return getInt("count");
	}
	
	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}
	
	/**
	 * 当前角色
	 */
	public M setRole(java.lang.String role) {
		set("role", role);
		return (M)this;
	}
	
	/**
	 * 当前角色
	 */
	public java.lang.String getRole() {
		return getStr("role");
	}
	
	public M setChatType(java.lang.String chatType) {
		set("chat_type", chatType);
		return (M)this;
	}
	
	public java.lang.String getChatType() {
		return getStr("chat_type");
	}
	
	public M setCarId(java.lang.Integer carId) {
		set("car_id", carId);
		return (M)this;
	}
	
	public java.lang.Integer getCarId() {
		return getInt("car_id");
	}
	
	public M setMessageId(java.lang.String messageId) {
		set("message_id", messageId);
		return (M)this;
	}
	
	public java.lang.String getMessageId() {
		return getStr("message_id");
	}
	
	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public M setAccessHash(java.lang.Long accessHash) {
		set("access_hash", accessHash);
		return (M)this;
	}
	
	public java.lang.Long getAccessHash() {
		return getLong("access_hash");
	}
	
	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	public M setIsAdmin(java.lang.Boolean isAdmin) {
		set("is_admin", isAdmin);
		return (M)this;
	}
	
	public java.lang.Boolean getIsAdmin() {
		return getBoolean("is_admin");
	}
	
}

