package com.litongjava.telegram.bot.model.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSetting<M extends BaseSetting<M>> extends Model<M> implements IBean {

	public M setSetKey(java.lang.String setKey) {
		set("set_key", setKey);
		return (M)this;
	}
	
	public java.lang.String getSetKey() {
		return getStr("set_key");
	}
	
	public M setSetValue(java.lang.String setValue) {
		set("set_value", setValue);
		return (M)this;
	}
	
	public java.lang.String getSetValue() {
		return getStr("set_value");
	}
	
	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
}

