package com.litongjava.telegram.bot.model.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTelegramState<M extends BaseTelegramState<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setPts(java.lang.Integer pts) {
		set("pts", pts);
		return (M)this;
	}
	
	public java.lang.Integer getPts() {
		return getInt("pts");
	}
	
	public M setQts(java.lang.Integer qts) {
		set("qts", qts);
		return (M)this;
	}
	
	public java.lang.Integer getQts() {
		return getInt("qts");
	}
	
	public M setDate(java.lang.Integer date) {
		set("date", date);
		return (M)this;
	}
	
	public java.lang.Integer getDate() {
		return getInt("date");
	}
	
	public M setSeq(java.lang.Integer seq) {
		set("seq", seq);
		return (M)this;
	}
	
	public java.lang.Integer getSeq() {
		return getInt("seq");
	}
	
	public M setUnreadCount(java.lang.Integer unreadCount) {
		set("unread_count", unreadCount);
		return (M)this;
	}
	
	public java.lang.Integer getUnreadCount() {
		return getInt("unread_count");
	}
	
	public M setCreator(java.lang.String creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public M setUpdater(java.lang.String updater) {
		set("updater", updater);
		return (M)this;
	}
	
	public java.lang.String getUpdater() {
		return getStr("updater");
	}
	
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	public M setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
		return (M)this;
	}
	
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
}

