package com.litongjava.telegram.bot.model.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserRole<M extends BaseUserRole<M>> extends Model<M> implements IBean {

	/**
	 * telegramid
	 */
	public M setTgId(java.lang.String tgId) {
		set("tg_id", tgId);
		return (M)this;
	}
	
	/**
	 * telegramid
	 */
	public java.lang.String getTgId() {
		return getStr("tg_id");
	}
	
	/**
	 * 当前的角色
	 */
	public M setRole(java.lang.String role) {
		set("role", role);
		return (M)this;
	}
	
	/**
	 * 当前的角色
	 */
	public java.lang.String getRole() {
		return getStr("role");
	}
	
	/**
	 * 创建时间
	 */
	public M setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	/**
	 * 更新时间
	 */
	public M setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

